- name: Configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable current nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: Create expense user
    ansible.builtin.user:
      name: expense
    
  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory